### ISSUE TITLE
Russian Language

### ISSUE THREAD

**Issue by ayayaQ** [ayayaQ/BotCommander_Languages#2]

**Comment by PadowYT2** [comment]
yes i will do it

**Comment by ayayaQ** [comment]
> yes i will do it

If you really will, I must update the strings in this repository first as they are a bit out of date and missing a few.

**Comment by ayayaQ** [comment]
I've updated them in 29879a6. So if you decide to do so there should be no missing strings.

**Comment by PadowYT2** [comment]
yes! thanks for the respond, ill do it in 2 days because phone sucks

**Comment by PadowYT2** [comment]
also, can you please read staff chat (im padowyt2)

**Comment by PadowYT2** [comment]
https://discord.com/channels/711481988938465340/712794443589353513/864354838891200553

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/711481988938465340/712794443589353513/865091598739570698

**Comment by PadowYT2** [comment]
hm? https://padow.why-am-i-he.re/54qwztcl8

**Comment by PadowYT2** [comment]
also https://padow.why-am-i-he.re/54qxk7LrB

**Comment by PadowYT2** [comment]
is it old

**Comment by PadowYT2** [comment]
also https://padow.why-am-i-he.re/54qxYBpSc

**Comment by PadowYT2** [comment]
and     <string name="home_message">Here is where you put your bot token given by Discord to host the bot. Commands must be added before hosting and changes to commands while hosting will only be seen when the bot is rehosted.</string>

**Comment by PadowYT2** [comment]
and
    <string name="channel_message_out">Channel Message: </string>
    <string name="pm_out">PM: </string>

**Comment by PadowYT2** [comment]
or is that old info too

**Comment by PadowYT2** [comment]
^^?

**Comment by ayayaQ** [comment]
Those are all still used.

**Comment by PadowYT2** [comment]
hm? but then where Icon of Command Type is used?

**Comment by PadowYT2** [comment]
cuz if i dont know that, i dont know how to translate it

**Comment by PadowYT2** [comment]
also `<string name="help_message">`

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/711481988938465340/712794443589353513/866623886115209266

**Comment by PadowYT2** [comment]
#5

**Comment by PadowYT2** [comment]
I think, this can be closed

**Comment by ayayaQ** [comment]
Correct. e10357bf2ffd7c75153beddc9c4af6da4a0d9ff7 concluded this issue.
