### ISSUE TITLE
Japanese Language

### ISSUE THREAD

**Issue by ayayaQ** [ayayaQ/BotCommander_Languages#4]
I'll attempt this localisation since I believe I may know enough to make a decent one.

**Comment by ayayaQ** [comment]
Progress is being made with 9f990fa2aded8a85719208f205940a24d4bb1ec8.

**Comment by PadowYT2** [comment]
you made it, close maybe?

**Comment by ayayaQ** [comment]
I'm going to update to the latest strings and then close this issue.

**Comment by ayayaQ** [comment]
Up to date with https://github.com/ayayaQ/BotCommander_Languages/commit/497b4cfba90a180471070ee18e97bb564725a887.
